### ISSUE TITLE
Assets are missing boost-program options

### ISSUE THREAD

**Issue by JasonMarechal25** [AntaresSimulatorTeam/antares-deps#22]
for ubuntu at least, when trying to build antares xpansion using antares deps assets Cmake can't find boost-program options 173. This specific package is missing from assets. Cmake try to use the system version but can't because of mismatch version number (173 vs 171)

Current workaround is to delete boost folder from antares deps downloaded assets so that cmake only use system packages.

**Comment by flomnes** [comment]
See the deps of [program_options](https://pdimov.github.io/boostdep-report/boost-1.79.0/program_options.html)
